export interface Food {
  name: string
  calories: number
  protein: number
  fiber: number
  vitaminScore: number
  category: string
  nutrition: number
}

export const foodDataset: Food[] = [
  {
    name: 'Grilled Chicken Breast',
    calories: 165,
    protein: 31,
    fiber: 0,
    vitaminScore: 85,
    category: 'Protein',
    nutrition: 92,
  },
  {
    name: 'Salmon Fillet',
    calories: 280,
    protein: 25,
    fiber: 0,
    vitaminScore: 88,
    category: 'Protein',
    nutrition: 95,
  },
  {
    name: 'Lean Beef',
    calories: 250,
    protein: 26,
    fiber: 0,
    vitaminScore: 80,
    category: 'Protein',
    nutrition: 88,
  },
  {
    name: 'Greek Yogurt',
    calories: 100,
    protein: 17,
    fiber: 0,
    vitaminScore: 75,
    category: 'Dairy',
    nutrition: 82,
  },
  {
    name: 'Cheddar Cheese',
    calories: 402,
    protein: 25,
    fiber: 0,
    vitaminScore: 70,
    category: 'Dairy',
    nutrition: 78,
  },
  {
    name: 'Whole Wheat Bread',
    calories: 80,
    protein: 4,
    fiber: 4,
    vitaminScore: 65,
    category: 'Grains',
    nutrition: 72,
  },
  {
    name: 'Brown Rice',
    calories: 111,
    protein: 2.6,
    fiber: 1.8,
    vitaminScore: 68,
    category: 'Grains',
    nutrition: 70,
  },
  {
    name: 'Oats',
    calories: 150,
    protein: 5,
    fiber: 8,
    vitaminScore: 72,
    category: 'Grains',
    nutrition: 75,
  },
  {
    name: 'Broccoli',
    calories: 34,
    protein: 2.8,
    fiber: 2.4,
    vitaminScore: 95,
    category: 'Vegetables',
    nutrition: 90,
  },
  {
    name: 'Spinach',
    calories: 23,
    protein: 2.9,
    fiber: 2.2,
    vitaminScore: 98,
    category: 'Vegetables',
    nutrition: 92,
  },
  {
    name: 'Carrot',
    calories: 41,
    protein: 0.9,
    fiber: 2.8,
    vitaminScore: 92,
    category: 'Vegetables',
    nutrition: 88,
  },
  {
    name: 'Bell Pepper',
    calories: 30,
    protein: 0.9,
    fiber: 1.9,
    vitaminScore: 90,
    category: 'Vegetables',
    nutrition: 87,
  },
  {
    name: 'Banana',
    calories: 89,
    protein: 1.1,
    fiber: 2.6,
    vitaminScore: 80,
    category: 'Fruits',
    nutrition: 82,
  },
  {
    name: 'Apple',
    calories: 52,
    protein: 0.3,
    fiber: 2.4,
    vitaminScore: 78,
    category: 'Fruits',
    nutrition: 80,
  },
  {
    name: 'Blueberries',
    calories: 57,
    protein: 0.7,
    fiber: 2.4,
    vitaminScore: 92,
    category: 'Fruits',
    nutrition: 88,
  },
  {
    name: 'Almonds',
    calories: 579,
    protein: 21,
    fiber: 12.5,
    vitaminScore: 85,
    category: 'Nuts',
    nutrition: 86,
  },
  {
    name: 'Walnuts',
    calories: 654,
    protein: 9,
    fiber: 6.7,
    vitaminScore: 82,
    category: 'Nuts',
    nutrition: 84,
  },
  {
    name: 'Lentils',
    calories: 116,
    protein: 9,
    fiber: 8,
    vitaminScore: 80,
    category: 'Legumes',
    nutrition: 85,
  },
  {
    name: 'Black Beans',
    calories: 132,
    protein: 8.9,
    fiber: 8.4,
    vitaminScore: 78,
    category: 'Legumes',
    nutrition: 83,
  },
  {
    name: 'Chickpeas',
    calories: 164,
    protein: 8.9,
    fiber: 7.6,
    vitaminScore: 76,
    category: 'Legumes',
    nutrition: 81,
  },
  {
    name: 'Olive Oil',
    calories: 884,
    protein: 0,
    fiber: 0,
    vitaminScore: 88,
    category: 'Healthy Fats',
    nutrition: 80,
  },
  {
    name: 'Avocado',
    calories: 160,
    protein: 2,
    fiber: 6.7,
    vitaminScore: 90,
    category: 'Healthy Fats',
    nutrition: 88,
  },
  {
    name: 'Coconut Oil',
    calories: 892,
    protein: 0,
    fiber: 0,
    vitaminScore: 70,
    category: 'Healthy Fats',
    nutrition: 72,
  },
]
